spring:
  application:
    name: tacobank_core_server
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://{DB_HOST}:{DB_PORT}/{DB_NAME}?useSSL=false&useServerPrepStmts=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: {DB_USERNAME}
    password: {DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MariaDBDialect

  data:
    redis:
      #      host: redis
      host: localhost
      port: 6379

management:
  prometheus:
    metrics:
      export:
        enabled: true
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    db:
      enabled: true  # 데이터베이스 연결 상태 확인


server:
  port: 8080


