spring:
  application:
    name: business_server
  datasource:
    url: jdbc:mariadb://localhost:3306/tacobank_db
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MariaDBDialect

  data:
    redis:
      #      host: redis
      host: localhost
      port: 6379

management:
  prometheus:
    metrics:
      export:
        enabled: true
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    db:
      enabled: true  # 데이터베이스 연결 상태 확인
    redis:
      enabled: true  # Redis 연결 상태 확인

server:
  port: 8081
