replicaCount: 4

image:
  repository: "485298580046.dkr.ecr.ap-northeast-2.amazonaws.com/taco_core"
  tag: "latest"
  pullPolicy: "IfNotPresent"

namespace: "taco-core"
createNamespace: false


service:
  type: NodePort
  port: 9002
  targetPort: 9002
  nodePort: 32000

ingress:
  enabled: true
  className: "alb"
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "ip"
    alb.ingress.kubernetes.io/actions.taco-core: '{"type":"forward","targetGroupArn":"arn:aws:elasticloadbalancing:ap-northeast-2:485298580046:targetgroup/taco-core-helm/38f37b96d7e184f8"}'
  hosts:
    - host: "almagest.io"
      paths:
        - path: "/"
          pathType: "Prefix"


resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

autoscaling:
  enabled: true
  minReplicas: 4
  maxReplicas: 8
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeAffinity:
  enabled: true
  requiredDuringSchedulingIgnoredDuringExecution:
    - key: "kubernetes.io/hostname"
      operator: "In"
      values:
        - "ip-172-31-21-139"
        - "ip-172-31-22-110"

env:
  DDL_TYPE: ""
  PROFILE: ""
  DB_HOST: ""
  DB_PORT: ""
  DB_NAME: ""
  DB_USERNAME: ""
  DB_PASSWORD: ""
  REDIS_HOST: ""
  REDIS_PORT: ""
  TACO_CORE_PORT: ""
  TESTBED_API_KEY: ""
  TACO_JWT_SECRET: ""
  TACO_JWT_EXP: ""
  TACO_ENC_KEY: ""
  TACO_NAVER_ACCESS_KEY: ""
  TACO_NAVER_SECRET_KEY: ""
  TACO_NAVER_SMS_ID: ""
  TACO_NAVER_SMS_FROM: ""
  TACO_NAVER_OCR_URL: ""
  TACO_NAVER_OCR_SECRET: ""
  AWS_S3_REGION: ""
  AWS_S3_BUCKET_NAME: ""
  AWS_S3_FOLDER_PATH_CORE: ""
  AWS_S3_IAM_ACCESS_KEY: ""
  AWS_S3_IAM_SECRET_KEY: ""


